ARG IMAGE_REPOSITORY
ARG IMAGE_REPOSITORY_SEPARATOR
# pull official base image, see https://hub.docker.com/r/zhicwu/prom/
FROM ${IMAGE_REPOSITORY}${IMAGE_REPOSITORY_SEPARATOR}nginx:stable-alpine

# See https://stackoverflow.com/questions/29261811/use-docker-compose-env-variable-in-dockerbuild-file
ARG PROXY_USER
ARG PROXY_PASSWORD
ARG PROXY_FQDN
ARG PROXY_PORT

ENV HTTP_PROXY="http://${PROXY_USER}:${PROXY_PASSWORD}@${PROXY_FQDN}:${PROXY_PORT}"
ENV HTTPS_PROXY="http://${PROXY_USER}:${PROXY_PASSWORD}@${PROXY_FQDN}:${PROXY_PORT}"

# set working directory
WORKDIR /etc/nginx

# add config
COPY ./nginx.dev.conf ./conf.d/default.conf

# expose port
EXPOSE 7080

# start app
ENTRYPOINT [ "nginx" ]
CMD [ "-g", "daemon off;" ]
