ARG IMAGE_REPOSITORY
ARG IMAGE_REPOSITORY_SEPARATOR
# pull official base image, see https://hub.docker.com/r/johannesjo/super-productivity
FROM ${IMAGE_REPOSITORY}${IMAGE_REPOSITORY_SEPARATOR}johannesjo/super-productivity:v7.11.5

# See https://stackoverflow.com/questions/29261811/use-docker-compose-env-variable-in-dockerbuild-file
ARG PROXY_USER
ARG PROXY_PASSWORD
ARG PROXY_FQDN
ARG PROXY_PORT

ENV HTTP_PROXY="http://${PROXY_USER}:${PROXY_PASSWORD}@${PROXY_FQDN}:${PROXY_PORT}"
ENV HTTPS_PROXY="http://${PROXY_USER}:${PROXY_PASSWORD}@${PROXY_FQDN}:${PROXY_PORT}"

# set working directory
# WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
# ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
# COPY package.json ./
# COPY yarn.lock ./
# RUN yarn install --silent

# COPY next.config.js ./next.config.js

# we use volumes instead of copy
# for live editing
# COPY . ./

# expose port
EXPOSE 80

# start app
CMD ["yarn", "start"]
